DNA_ReverseCompliment = {"A": "T", "T": "A", "G": "C", "C": "G"}


def reverse_compliment(seq):
    """Finds complimentary base pairs and reverses list"""
    return "".join([DNA_ReverseCompliment[nuc] for nuc in seq])[::-1]  # Reverses the list


s = "TGTCCGTTACGACACGATGATCGCCCACCATATTGACCCTAGTACTCTTCTGTGGGTGTTTCTTAACATCAGGTTCGCAGGTGCTTGGCGTAAAAACGGCGCGAATCTTT" \
    "TCCCACTCAAGACTACATAAGCGAAGCATAGGCTCCGGAAACGTCGGACTAGGTCCAGTTACTTCACGTTAACCGGGGCTGCGCCAGCCTTGAGCTCTCAATACATTTGG" \
    "TATAGCGCAAACATTCGCTACTAACTTAACCCTTTTAAGTAGATTCCTACGGGGCCTGATCATGCATATTAAGCTTTTAACCATCTCAACATGTGACACACCTCCCCTAA" \
    "GCAACCCTGCGTCACCTTAAAATTCGTGAAACTAAGCCACAGCTCTCCAAGAGGAGTGGCGTATAGTTCCGGGGGCAAATGGGATTAGACCCGCCCGTCAATACGCCCCT" \
    "TGACGACCACGCGATTATCTGCGTGATCTCCCGCACTCAATCAGTCCCCGTCGGACGCTGCTAGTACTAACTAAGTGGCAGCGCGTACATGTGCCGCGTCACCTGGACAT" \
    "CCTCCATTAGACCGCGTCGCTCGGGATTAGAACCTTGTGATCCACGTCACCGGGTAATGACGTAGCCTAGTGTTGGGTGATGGAACGTGCATGAGTGGGCAGGGGCAGCT" \
    "ACGAGCGGCGGGCCAATAATCACGATTCGAACGCCGGCGCGACACGGTCGTACGTAAAATAAGTAACTCCGAGAGCCAATTCTATCTCCCTTCGCCGACGCCGCAATAAT" \
    "TATGATGCAGCAGCGAAGTGAATAAGGCAGGCCGTGCTGTCTAGCTCCTCTAATATCTTTCCCGGTCATGTTTCCTGTACCGATAACTAGGGAGAGTTTGGACCTAAAGT" \
    "GTGCTAAGTATTAGTAGTAGTCAGGAGACGTCACCTCCTATGATGTTTGAAGTCTATA"

print(reverse_compliment(s))
