def transcription(seq):
    """DNA to RNA translation. Replaces Thymine with Uracil"""
    return seq.replace("T", "U")


s = "CAAATCGCGGCCTAGCTATTCACCTATCTAGTCTTCTCTCTCTTTGTTCATCGATGGGATTAGAACACGATATTCGCGCATGGGGTAATTGGATCAACTACTAAACGTT" \
    "GCAGCGTGAGCTCAGATTTATACTTTAAGGCGAGACGTACCTTCAAGGACGTAAGTGCTGAGCTGCGCATCAGATCTTTGTCCCATTTGAATCTATTATGTCGCCAGCA" \
    "AAACCACGGACTGACTACTCCATAGCCGACGAAGTCAAAGGCTGCCGTTATGGCCAGAGCCCAAGACCCTACAGGTGTACCTCCCGCAACGCCCGCATTGATCGTCCTC" \
    "GACTGTCCCCGCGCTTTTGCAGGATTGGTATGGTAGTAGTCACTCCGATTTAATCCCAGCCGGCGTACCACATTCTGTTCTTTCTTCGTCTGAGATGGCCTTAGCGTTC" \
    "GGTGAGTCGGTCGTTTTAGCTGAGCTCTCTCTCTAAGTTCGGGTGCACGATAAACGCCTCACATAATATCACGGTTTGGGTAGTGTCCAGGTCGGATGGATTCCATTTT" \
    "TTGGATCGTGACGCATGATGAAGGTTTCCGGACGCATGGGACTTATGTTAACTACAAATGACGGACGGTTCCTCGCGCACGGATTATTAAAGCACACAGGCTTACTAGC" \
    "AATTAAACTGTCTACGGCTGTTGCCCGAGACCATGCATGCGCAAGCGAGGTGCTCGAAGTTGCCCAATTGTAGGCTACATTCTTAGTACGTTATAATTGGCGAGTATGA" \
    "GAGGTCAGTTCGACGTCAACTGGTGATCGCACGCTTTCAGCGATACGCGTCCGGAGATCTTAAATATTGGTTCAAATGCACCTCCCAGCGGTCGCTGCAAACATAAATC" \
    "CGGCAGGAGCTGAACCGGGTGGATCCCAGCTACCGACTTATGTTTGCGGGGAATAGACTAAGTTCTGAAGTTCGCAAGTCTGGTTCTAGCTGAG"

print(transcription(s))